### PR TITLE
registration template

### PR DESCRIPTION
**Pull request by shawn-mit**
# Description
This is the template for the registration page and setup for url routing 
# Related Ticket(s)
#27 
## Testing

[x ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[ x] I certify that all existing tests pass

## Documentation

[ ] There is new documentation in this pull request that must be reviewed..

## Deploy Notes
None

```sh
git pull --prune
git checkout <feature_branch>
```

## Steps to Test
Outline the steps to test the code in this pull request.

1.

### CODE REVIEW

**Review by ben-d-marks — COMMENTED** [review]
This is what we need. Thanks 👍

**Review by danirenae — APPROVED** [review]
looks great! 🚀

**Review by danirenae — CHANGES_REQUESTED** [review]
can you please change line 6 to say bangazon_ui instead of bangazon_ui_app

**Review by ben-d-marks — COMMENTED** [review]
👍

**Review by danirenae — APPROVED** [review]
👍

**Pull request merged**
