### PR TITLE
order_detail_view 

### PR DESCRIPTION
**Pull request by juliakimchung**
# Description
updated order_detail_view with closing method -corrected current_order statement, created redirect_to after logout
# Related Ticket(s)
#12 #23 

## Testing

[x ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[x ] I certify that all existing tests pass

## Documentation

[ x] There is new documentation in this pull request that must be reviewed..

## Steps to Test

1. login as a user
2 go to the browser to create product and add to order
3 logout

### CODE REVIEW

**Review by danirenae — CHANGES_REQUESTED** [review]
I logged in and routed to /add_to_order and /create_product and got 404 errors for both. I then routed to /product and successfully added an order. Please fix the routing if you would like it to go to /add_to_order and /create_product instead of /product (where it goes now)

**Comment by juliakimchung** [comment]
there's no create_product routing any more 
add_to_order is currently under work by Ben

**Review by danirenae — APPROVED** [review]

**Comment by danirenae** [comment]
Please let us know what to check in PR's! :) Looks good 👍

**Comment by pinkston4** [comment]
👍

**Pull request merged**
